### ISSUE TITLE
doubled up order taxonomies

### ISSUE THREAD

**Issue by dougwyu** [RTRichar/CurateDB#2]
Hi there,
I ran the test dataset, and i observed this in Test.tax

```
> L11684.1	k__Eukaryota;p__Streptophyta;c__urs_o__Gentianales;o__Gentianales;f__Gentianaceae;g__Exacum;s__Exacum affine;
> AB088829.1	k__Eukaryota;p__Streptophyta;c__Liliopsida;o__Commelinales;f__Haemodoraceae;g__Anigozanthos;s__Anigozanthos flavidus;

```

o_Gentianales is doubled up.  Is this correct behavior when the class is missing?

**Comment by RTRichar** [comment]
Hi @dougwyu, thanks for your comment. This is my personal preference for fixing nodes which are unresolved in the NCBI tree. Instead of having many potentially non-monophyletic groups with the same unresolved tag, or having every such lineage receive a distinct tag, the software pulls up the name from the lowest resolution rank containing an annotation and puts the 'urs' note on the annotation to designate 'unresolved'. Though I've never tested directly, you can imagine how such unresolved tags could confuse the classification process for some hierarchical classifiers. This feature can be disabled using the '--CleanTax F' argument. Using this won't change the test set outcome though, as those taxonomies were 'cleaned' prior to inclusion in the package as input.

**Comment by dougwyu** [comment]
thanks for the explanation!
