### ISSUE TITLE
choosing reference sequences

### ISSUE THREAD

**Issue by dleopold** [RTRichar/CurateDB#7]
I am interested to know why so few sequences are used for the initial set of reference sequences in MetaCurator and how much impact the choice of reference sequences is likely to have on the results. I ask because I am building a large number of reference databases and would like to automate the choice of reference sequences if possible. It is simple enough to take the larger set of all "uncurated" sequences that will be used and extract the region of interest from any sequences where the both primers can be found. Often this results in a very large number of potential reference sequences. Randomly choosing sequences seems unlikely to capture the potential range of diversity because many groups of taxa are over-represented, but maybe that is ok because the flanking / priming regions are going to be fairly conserved? Or do you think it is necessary to try and maximize diversity within the reference set in some way? Also, is it acceptable to use more than 5-10 reference sequences? Your thoughts on this would be greatly appreciated. Thank you. -Devin

**Comment by RTRichar** [comment]
Hi Devin, I haven't tried a very wide range of starting sequences but did test this to some extant in Supplemental Figure S3 of the manuscript. Starting with a very large number of references might not work well, especially if they are not trimmed to the exact region of interest, since the whole process if highly dependent on producing an accurate MAFFT multiple sequence alignment of the starting sequences. While experimenting with the process, you can use the --SaveTemp option to save all intermediate files, which would allow you to visually inspect that multiple sequence alignment and gauge performance. Generally, I would recommend starting with a diverse set. It didn't end up mattering in the tests I ran but it won't hurt and may be beneficial for markers with higher degrees of variation.
